image:
  repository: quay.io/keycloak/keycloak
  tag: 26.6.1
  pullPolicy: IfNotPresent

auth:
  adminPassword: ""
  clientSecret: ""
  demoAdminPassword: ""
  demoUserPassword: ""
  dbPassword: ""

route:
  enabled: true

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

setup:
  enabled: true
  image:
    repository: registry.redhat.io/ubi9/python-311
    tag: latest
    pullPolicy: IfNotPresent
  backoffLimit: 5
