name: 'Setup CI Environment'
description: 'Sets up runner with container images and environment for CI jobs'
inputs:
  catalog_image:
    description: 'OLM catalog image'
    required: false
    default: ''
  llama_stack_image:
    description: 'LLS distro image (extracted from catalog if not provided)'
    required: false
    default: ''
  operator_image:
    description: 'Operator image (extracted from catalog if not provided)'
    required: false
    default: ''
  env:
    description: 'Environment variables (multiline)'
    required: false
    default: ''
outputs:
  scripts_dir:
    description: 'Directory containing provision.sh, test.sh, cleanup.sh'
    value: ${{ steps.setup.outputs.scripts_dir }}
  env_file:
    description: 'Path to file containing environment variables'
    value: ${{ steps.setup.outputs.env_file }}
runs:
  using: 'composite'
  steps:
    - name: Setup runner environment
      id: setup
      shell: bash
      env:
        CATALOG_IMAGE: ${{ inputs.catalog_image }}
        LLAMA_STACK_IMAGE: ${{ inputs.llama_stack_image }}
        OPERATOR_IMAGE: ${{ inputs.operator_image }}
        ENV_VARS: ${{ inputs.env }}
      run: |
        chmod +x ${{ github.action_path }}/setup.sh
        ENV_FILE="/tmp/ci_env_$(date +%s).sh"
        export ENV_FILE
        ${{ github.action_path }}/setup.sh
        echo "scripts_dir=${{ github.action_path }}" >> $GITHUB_OUTPUT
        echo "env_file=$ENV_FILE" >> $GITHUB_OUTPUT
