{{- if .Values.dscinitialization.enabled }}
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: {{ .Values.dscinitialization.name }}
  labels:
    app.kubernetes.io/name: dscinitialization
    {{- include "llama-stack-rhoai.labels" . | nindent 4 }}
spec:
  applicationsNamespace: {{ .Release.Namespace }}
  monitoring:
    managementState: Removed
  serviceMesh:
    managementState: Removed
  trustedCABundle:
    managementState: Removed
{{- end }}
