{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.llamastack.name }}
  labels:
    app: {{ .Values.llamastack.name }}
    {{- include "llama-stack-rhoai.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Values.llamastack.name }}-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
