{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "keycloak.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $existing }}
  KEYCLOAK_ADMIN_LOGIN: {{ index $existing.data "KEYCLOAK_ADMIN_LOGIN" }}
  KEYCLOAK_CLIENT_SECRET: {{ index $existing.data "KEYCLOAK_CLIENT_SECRET" }}
  KEYCLOAK_ADMIN_PASSWORD: {{ index $existing.data "KEYCLOAK_ADMIN_PASSWORD" }}
  KEYCLOAK_DEVELOPER_PASSWORD: {{ index $existing.data "KEYCLOAK_DEVELOPER_PASSWORD" }}
  KEYCLOAK_DEVELOPER2_PASSWORD: {{ index $existing.data "KEYCLOAK_DEVELOPER2_PASSWORD" }}
  KEYCLOAK_USER_PASSWORD: {{ index $existing.data "KEYCLOAK_USER_PASSWORD" }}
  KEYCLOAK_USER2_PASSWORD: {{ index $existing.data "KEYCLOAK_USER2_PASSWORD" }}
  {{- else }}
  KEYCLOAK_ADMIN_LOGIN: {{ (.Values.auth.adminLogin | default (randAlphaNum 16)) | b64enc }}
  KEYCLOAK_CLIENT_SECRET: {{ (.Values.auth.clientSecret | default (randAlphaNum 32)) | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ (.Values.auth.adminPassword | default (randAlphaNum 12)) | b64enc }}
  KEYCLOAK_DEVELOPER_PASSWORD: {{ (.Values.auth.developerPassword | default (randAlphaNum 12)) | b64enc }}
  KEYCLOAK_DEVELOPER2_PASSWORD: {{ (.Values.auth.developer2Password | default (randAlphaNum 12)) | b64enc }}
  KEYCLOAK_USER_PASSWORD: {{ (.Values.auth.userPassword | default (randAlphaNum 12)) | b64enc }}
  KEYCLOAK_USER2_PASSWORD: {{ (.Values.auth.user2Password | default (randAlphaNum 12)) | b64enc }}
  {{- end }}
