{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "keycloak.dbSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.dbSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  KEYCLOAK_DB_USERNAME: {{ "keycloak" | b64enc }}
  {{- if $existing }}
  KEYCLOAK_DB_PASSWORD: {{ index $existing.data "KEYCLOAK_DB_PASSWORD" }}
  {{- else if .Values.auth.dbPassword }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.auth.dbPassword | b64enc }}
  {{- else }}
  KEYCLOAK_DB_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
