apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
