{{- if not .Values.auth.existingSecret }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "minio.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.secretName" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.auth.rootUser | b64enc }}
  {{- if $existing }}
  MINIO_ROOT_PASSWORD: {{ index $existing.data "MINIO_ROOT_PASSWORD" }}
  {{- else if .Values.auth.rootPassword }}
  MINIO_ROOT_PASSWORD: {{ .Values.auth.rootPassword | b64enc }}
  {{- else }}
  MINIO_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
{{- end }}
