apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-distribution
spec:
  replicas: 1
  server:
    containerSpec:
      env:
      - name: INFERENCE_MODEL
        value: ${INFERENCE_MODEL}
      - name: VLLM_API_TOKEN
        value: ${SHOWROOM_VLLM_API_TOKEN}
      - name: VLLM_URL
        value: ${SHOWROOM_VLLM_URL}
      - name: EMBEDDING_MODEL
        value: ${EMBEDDING_MODEL}
      - name: EMBEDDING_PROVIDER
        value: vllm-embedding
      - name: EMBEDDING_PROVIDER_MODEL_ID
        value: ${EMBEDDING_PROVIDER_MODEL_ID}
      - name: EMBEDDING_DIMENSION
        value: ${EMBEDDING_DIMENSION}
      - name: VLLM_EMBEDDING_URL
        value: ${SHOWROOM_VLLM_EMBEDDING_URL}
      - name: VLLM_EMBEDDING_API_TOKEN
        value: ${SHOWROOM_VLLM_EMBEDDING_API_TOKEN}
      - name: VLLM_EMBEDDING_MAX_TOKENS
        value: "4096"
      - name: VLLM_EMBEDDING_TLS_VERIFY
        value: "true"
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_DB
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
      # Keycloak OAuth/OIDC Configuration for ABAC
      - name: KEYCLOAK_URL
        value: http://keycloak:8080
      - name: KEYCLOAK_ISSUER_URL
        value: http://keycloak:8080
      - name: KEYCLOAK_VERIFY_TLS
        value: "false"
      name: llama-stack
      port: 8321
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
    distribution:
      name: rh-dev
    # Reference the ConfigMap with the llama-stack configuration
    userConfig:
      configMapName: llamastack-config
