image:
  repository: quay.io/rh-aiservices-bu/milvus-openshift
  tag: v2.6.15-multiarch
  pullPolicy: IfNotPresent

persistence:
  size: 10Gi

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
