image:
  repository: quay.io/coreos/etcd
  tag: v3.5.25
  pullPolicy: IfNotPresent

persistence:
  size: 2Gi

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
