apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  ports:
    - port: 2379
      targetPort: 2379
      name: client
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
