image:
  repository: quay.io/ehu-aaet3/imagehost
  tag: milvus-2.5.26
  pullPolicy: IfNotPresent

persistence:
  size: 10Gi

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
