apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add imagePullSecrets
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Workaround https://issues.redhat.com/browse/OCPBUGS-23901,
      use the secret in all Pods.
spec:
  failurePolicy: Ignore
  rules:
  - name: add-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{ images.initContainers.*.registry || `[]` }}"
        operator: AnyIn
        value:
        - brew.registry.redhat.io
        - quay.io
        - registry.stage.redhat.io
        - registry-proxy.engineering.redhat.com
        - registry.redhat.io
      - key: "{{ images.containers.*.registry }}"
        operator: AnyIn
        value:
        - brew.registry.redhat.io
        - quay.io
        - registry.stage.redhat.io
        - registry-proxy.engineering.redhat.com
        - registry.redhat.io
    mutate:
      patchesJson6902: |-
        - path: "/spec/imagePullSecrets/-"
          op: add
          value:
            name: pull-secret-brew
        - path: "/metadata/labels/kyverno-add-imagepullsecret"
          op: add
          value: was-here
