{{- if not .Values.auth.existingSecret }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "postgres.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  POSTGRES_USER: {{ .Values.auth.username | b64enc }}
  POSTGRES_DB: {{ .Values.auth.database | b64enc }}
  {{- if $existing }}
  POSTGRES_PASSWORD: {{ index $existing.data "POSTGRES_PASSWORD" }}
  {{- else if .Values.auth.password }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
{{- end }}
