apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
- dscinitialization.yaml
- datasciencecluster.yaml
- keycloak.yaml
- postgres.yaml
- etcd.yaml
- etcd-networkpolicy.yaml
- milvus.yaml
- milvus-networkpolicy.yaml
- minio.yaml
- minio-networkpolicy.yaml
- minio-route.yaml
- networkpolicy.yaml
- route.yaml
