apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: milvus-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: milvus
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 19530
      protocol: TCP
    - port: 9091
      protocol: TCP
